name: Dotty - Check for new core technologies

on:
  schedule:
   - cron:  '0 10 1,15 * *' # On the 1st and 15th of every month at 10:00 AM UTC
  workflow_dispatch:
    inputs:
      daysToSearch:
        description: "Days of NuGet history to search for package updates (0 to search since last run of this workflow on main)"
        default: "0"
        type: string
      testMode:
        description: "If checked, no notification message will be sent to the team channel, nor will any Github issues be created."
        type: boolean
        default: false

env:
  DOTNET_NOLOGO: true

permissions:
  contents: read

jobs:
  run-dotty:
    name: Check for core technology package updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    continue-on-error: false
    
    env:
      dotty-path: ${{ github.workspace }}/build/Dotty
      dotty-publish-path: ${{ github.workspace }}/publish

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit # Leave it audit mode

      - name: Install .NET 10
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'ga'

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Add agent via nuget and then build Dotty
        run: |
          cd ${{ env.dotty-path }}
          dotnet add Dotty.csproj package NewRelic.Agent
          dotnet publish -o ${{ env.dotty-publish-path }}

      - name: Find timestamp of most recent run of this workflow and set as an environment variable
        if: inputs.daysToSearch == '0' || github.event_name == 'schedule'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
           echo "LAST_RUN_TIMESTAMP=$(gh run list --workflow dotty.yml --branch main --status completed --limit 1 --json updatedAt | jq -r '.[0].updatedAt')" >> $GITHUB_ENV
        shell: bash

      - name: Check for updates to core technology packages
        env:
          DOTTY_WEBHOOK: ${{ secrets.SLACK_NUGET_NOTIFICATIONS_WEBHOOK }}
          DOTTY_TOKEN: ${{ secrets.DOTNET_AGENT_GH_TOKEN }}
          CORECLR_ENABLE_PROFILING: 1
          CORECLR_NEW_RELIC_HOME: ${{ env.dotty-publish-path }}/newrelic
          CORECLR_PROFILER: "{36032161-FFC0-4B61-B559-F6C5D41BAE5A}"
          CORECLR_PROFILER_PATH: ${{ env.dotty-publish-path }}/newrelic/libNewRelicProfiler.so
          NEW_RELIC_APP_NAME: Dotty
          NEW_RELIC_HOST: staging-collector.newrelic.com
          NEW_RELIC_LICENSE_KEY: ${{ secrets.STAGING_LICENSE_KEY }}
          DOTTY_LAST_RUN_TIMESTAMP: ${{ env.LAST_RUN_TIMESTAMP }}
          DOTTY_SEARCH_ROOT_PATH: ${{ github.workspace }}

        run: |
          if [ ${{ inputs.daysToSearch }} != "" ]; then
            export DOTTY_DAYS_TO_SEARCH=${{ inputs.daysToSearch }}
          fi
          if [ "${{ inputs.testMode }}" == "true" ]; then
            export DOTTY_TEST_MODE="True"
          fi
          cd ${{ env.dotty-publish-path }}
          dotnet ./Dotty.dll
        shell: bash
        
