name: Check Markdown links

on: push

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # intentionally disabled, as the links in our markdown docs grow, we would constantly need to update the allowed endpoints for this step.
    # - name: Harden Runner
    #   uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
    #   with:
    #     egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
      with:
        #use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdowncheck.config.json'
        #max-depth: 2