# This is a basic workflow to help you get started with Actions

name: Second Workflow

on:
  workflow_run:
    workflows: ['First Workflow']
    types: ['completed']

jobs:
  get-info:
    name: "Get information about the source run"
    runs-on: ubuntu-latest
    outputs:
      sourceEvent: ${{ steps.source-run-info.outputs.sourceEvent }}
    steps:
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

  build:
    needs: get-info
    if: ${{ needs.get-info.outputs.sourceEvent == 'release' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Download agent-version Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: first.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: agent-version
          path: ${{ github.workspace }}
          repo: ${{ github.repository }}
    
      - name: Run a one-line script
        run: |
          ls -la
          echo ${{ github.event.workflow_run.id }}
