name: Test 01

on:
  workflow_dispatch:
    inputs:
      agent_version:
        description: 'version x.x.x'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Do Work
        run: |
          AGENT_VERSION="${{ github.event.inputs.agent_version }}"
          AGENT_VERSION_V="${{ github.event.inputs.agent_version }}"
          cd wiki
          cd mvs
          if [[ ! -d "$AGENT_VERSION_V" ]]; then
            mkdir "AGENT_VERSION_V"
            touch $AGENT_VERSION_V/${AGENT_VERSION_V}-Home.md
          fi
          cd "AGENT_VERSION_V"
          pwd
          ls -la
      - name: Push to wiki
        run: |
          cd wiki
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          # git add .
          # git diff-index --quiet HEAD || git commit -m "Add changes" && git push
